#!/bin/bash
options="power-shutdown\npower-reboot\npower-sleep"
choice=$(echo -e "$options" | dmenu -b -i -p "power:")
case "$choice" in
    power-shutdown)
        systemctl poweroff ;;
    power-reboot)
        systemctl reboot ;;
    power-sleep)
        systemctl suspend ;;
esac
